// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Wed Dec 15 12:23:47 2021

ADC_CONTROL ADC_CONTROL_inst
(
	.iCLK(iCLK_sig) ,	// input  iCLK_sig
	.iRST_n(iRST_n_sig) ,	// input  iRST_n_sig
	.oADC_DIN(oADC_DIN_sig) ,	// output  oADC_DIN_sig
	.oADC_DCLK(oADC_DCLK_sig) ,	// output  oADC_DCLK_sig
	.oSCEN(oSCEN_sig) ,	// output  oSCEN_sig
	.iADC_DOUT(iADC_DOUT_sig) ,	// input  iADC_DOUT_sig
	.iADC_BUSY(iADC_BUSY_sig) ,	// input  iADC_BUSY_sig
	.iADC_PENIRQ_n(iADC_PENIRQ_n_sig) ,	// input  iADC_PENIRQ_n_sig
	.oX_COORD(oX_COORD_sig) ,	// output [11:0] oX_COORD_sig
	.oY_COORD(oY_COORD_sig) 	// output [11:0] oY_COORD_sig
);

defparam ADC_CONTROL_inst.SYSCLK_FRQ = 50000000;
defparam ADC_CONTROL_inst.ADC_DCLK_FRQ = 70000;
//defparam ADC_CONTROL_inst.ADC_DCLK_CNT = ;
