// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Nov 02 18:44:27 2021

n_counter n_counter_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.enable(enable_sig) ,	// input  enable_sig
	.up_down(up_down_sig) ,	// input  up_down_sig
	.count(count_sig) ,	// output [N-1:0] count_sig
	.TC(TC_sig) 	// output  TC_sig
);

defparam n_counter_inst.fin_cuenta = 16;
//defparam n_counter_inst.N = ;
