// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Nov 16 17:59:33 2021

barras_lcd barras_lcd_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST(RST_sig) ,	// input  RST_sig
	.NCLK(NCLK_sig) ,	// output  NCLK_sig
	.GREST(GREST_sig) ,	// output  GREST_sig
	.HD(HD_sig) ,	// output  HD_sig
	.VD(VD_sig) ,	// output  VD_sig
	.DEN(DEN_sig) ,	// output  DEN_sig
	.R(R_sig) ,	// output [7:0] R_sig
	.G(G_sig) ,	// output [7:0] G_sig
	.B(B_sig) 	// output [7:0] B_sig
);

