// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Nov 30 17:54:03 2021

char_rom char_rom_inst
(
	.NCLK(NCLK_sig) ,	// input  NCLK_sig
	.fila(fila_sig) ,	// input [9:0] fila_sig
	.columna(columna_sig) ,	// input [10:0] columna_sig
	.caracter(caracter_sig) ,	// input [5:0] caracter_sig
	.pixel_on_off(pixel_on_off_sig) 	// output  pixel_on_off_sig
);

