// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Nov 15 23:27:34 2021

lcd_sync lcd_sync_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST_N(RST_N_sig) ,	// input  RST_N_sig
	.NCLK(NCLK_sig) ,	// output  NCLK_sig
	.GREST(GREST_sig) ,	// output  GREST_sig
	.HD(HD_sig) ,	// output  HD_sig
	.VD(VD_sig) ,	// output  VD_sig
	.DEN(DEN_sig) ,	// output  DEN_sig
	.fila(fila_sig) ,	// output [10:0] fila_sig
	.columna(columna_sig) 	// output [9:0] columna_sig
);

