// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Nov 02 16:32:34 2021

Practica_FSM Practica_FSM_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.up_down(up_down_sig) ,	// input  up_down_sig
	.enable(enable_sig) ,	// input  enable_sig
	.seq(seq_sig) 	// output [3:0] seq_sig
);

defparam Practica_FSM_inst.S0 = 'b0000;
defparam Practica_FSM_inst.S1 = 'b0010;
defparam Practica_FSM_inst.S2 = 'b0011;
defparam Practica_FSM_inst.S3 = 'b0101;
defparam Practica_FSM_inst.S4 = 'b0111;
defparam Practica_FSM_inst.S5 = 'b1010;
